var now = new Date();
document.write("<b>Date Functions<b><br>");
document.write(now + "<br>");
document.write(now.toDateString() + "<br>");
document.write(now.getDate() + "<br>");
document.write(now.getFullYear() + "<br>");
document.write(now.getMonth() + "<br>");
document.write(now.getDay() + "<br>");
document.write("<b>Time Functions</b><br>");
document.write(now.getHours() + "<br>");
document.write(now.getMinutes() + "<br>");
document.write(now.getSeconds() + "<br>");
document.write(now.getMilliseconds() + "<br>");
document.write("<br>");
now.setFullYear(2023);
document.write(now + "<br>");
document.write(now.toDateString() + "<br>");
document.write(now.getDate() + "<br>");
document.write(now.getFullYear() + "<br>");
document.write(now.getMonth() + "<br>");
document.write(now.getDay() + "<br>");
document.write("<b>Time Functions</b><br>");
document.write(now.getHours() + "<br>");
document.write(now.getMinutes() + "<br>");
document.write(now.getSeconds() + "<br>");
document.write(now.getMilliseconds() + "<br>");
